---
- name: Device Specific Provisioning
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Common - Install basic tools
      apt:
        name: [htop, neofetch, vim, tree]
        state: present
        update_cache: yes

    - name: VM Specific - Install QEMU Guest Agent
      apt:
        name: qemu-guest-agent
        state: present
      when: ansible_hostname == "zatestvmtest01"

    - name: Identity - Create a customized motd
      copy:
        content: "Welcome to {{ ansible_hostname }}. Managed by Ansible Pull.\n"
        dest: /etc/motd
